// <auto-generated />
using System;
using Accredit.Domain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Accredit.Domain.Migrations
{
    [DbContext(typeof(HumanResourceContext))]
    [Migration("20211128205644_AddSeedData")]
    partial class AddSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Accredit.Shared.Entities.HumanResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("HumanResourceStatusId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("HumanResourceStatusId");

                    b.ToTable("HumanResources");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b324046e-fcdd-4133-bb16-7f39ebbd2f0a"),
                            CreatedDate = new DateTime(2021, 11, 28, 20, 56, 43, 495, DateTimeKind.Local).AddTicks(7023),
                            DateOfBirth = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "IT",
                            Email = "jbloggs@hr.com",
                            EmployeeNumber = "01",
                            FirstName = "Joe Bloggs",
                            HumanResourceStatusId = 1,
                            LastName = "Bloggs"
                        },
                        new
                        {
                            Id = new Guid("b76758c4-0209-49cf-b33c-5117e64ec254"),
                            CreatedDate = new DateTime(2021, 11, 28, 20, 56, 43, 496, DateTimeKind.Local).AddTicks(6713),
                            DateOfBirth = new DateTime(1984, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Marketing",
                            Email = "shayes@hr.com",
                            EmployeeNumber = "02",
                            FirstName = "Simon",
                            HumanResourceStatusId = 3,
                            LastName = "Hayes"
                        });
                });

            modelBuilder.Entity("Accredit.Shared.Entities.HumanResourceStatus", b =>
                {
                    b.Property<int>("HumanResourceStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HumanResourceStatusId");

                    b.ToTable("HumanResourceStatus");

                    b.HasData(
                        new
                        {
                            HumanResourceStatusId = 1,
                            Name = "Approved"
                        },
                        new
                        {
                            HumanResourceStatusId = 2,
                            Name = "Pending"
                        },
                        new
                        {
                            HumanResourceStatusId = 3,
                            Name = "Disabled"
                        });
                });

            modelBuilder.Entity("Accredit.Shared.Entities.HumanResource", b =>
                {
                    b.HasOne("Accredit.Shared.Entities.HumanResourceStatus", "HumanResourceStatus")
                        .WithMany("HumanResources")
                        .HasForeignKey("HumanResourceStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
