// <auto-generated />
using System;
using Accredit.Domain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Accredit.Domain.Migrations
{
    [DbContext(typeof(HumanResourceContext))]
    [Migration("20211129223257_ExtendSeedData")]
    partial class ExtendSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Accredit.Shared.Entities.HumanResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("HumanResourceStatusId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("HumanResourceStatusId");

                    b.ToTable("HumanResources");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c975dda4-77a4-459a-8454-4cad23bfc5d5"),
                            CreatedDate = new DateTime(2021, 11, 29, 22, 32, 56, 850, DateTimeKind.Local).AddTicks(4225),
                            DateOfBirth = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "IT",
                            Email = "jbloggs@hr.com",
                            EmployeeNumber = "01",
                            FirstName = "Joe",
                            HumanResourceStatusId = 1,
                            LastName = "Bloggs"
                        },
                        new
                        {
                            Id = new Guid("f6ae1fdf-9aa0-4606-8ead-c13ae4c5340b"),
                            CreatedDate = new DateTime(2021, 11, 29, 22, 32, 56, 851, DateTimeKind.Local).AddTicks(568),
                            DateOfBirth = new DateTime(2002, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Sales",
                            Email = "hpatel@hr.com",
                            EmployeeNumber = "03",
                            FirstName = "Harvey",
                            HumanResourceStatusId = 3,
                            LastName = "Patel"
                        },
                        new
                        {
                            Id = new Guid("156d294c-5636-467e-90c7-7cbcbb14e6a6"),
                            CreatedDate = new DateTime(2021, 11, 29, 22, 32, 56, 851, DateTimeKind.Local).AddTicks(670),
                            DateOfBirth = new DateTime(1984, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Marketing",
                            Email = "shayes@hr.com",
                            EmployeeNumber = "03",
                            FirstName = "Simon",
                            HumanResourceStatusId = 1,
                            LastName = "Hayes"
                        },
                        new
                        {
                            Id = new Guid("2e8a2917-3ce0-4c93-ba64-129e80b42f71"),
                            CreatedDate = new DateTime(2021, 11, 29, 22, 32, 56, 851, DateTimeKind.Local).AddTicks(685),
                            DateOfBirth = new DateTime(1978, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "IT",
                            Email = "zmurphy@hr.com",
                            EmployeeNumber = "04",
                            FirstName = "Zoe",
                            HumanResourceStatusId = 2,
                            LastName = "Murphy"
                        },
                        new
                        {
                            Id = new Guid("ba65a8bf-ed2a-4dff-bdd7-86ff59205263"),
                            CreatedDate = new DateTime(2021, 11, 29, 22, 32, 56, 851, DateTimeKind.Local).AddTicks(699),
                            DateOfBirth = new DateTime(1994, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Call Center",
                            Email = "chawkins@hr.com",
                            EmployeeNumber = "05",
                            FirstName = "Charlie",
                            HumanResourceStatusId = 1,
                            LastName = "Hawkins"
                        },
                        new
                        {
                            Id = new Guid("44448dc6-daf6-4728-92df-c54e6aebd955"),
                            CreatedDate = new DateTime(2021, 11, 29, 22, 32, 56, 851, DateTimeKind.Local).AddTicks(712),
                            DateOfBirth = new DateTime(1982, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "IT",
                            Email = "abishop@hr.com",
                            EmployeeNumber = "06",
                            FirstName = "Alisha",
                            HumanResourceStatusId = 1,
                            LastName = "Bishop"
                        });
                });

            modelBuilder.Entity("Accredit.Shared.Entities.HumanResourceStatus", b =>
                {
                    b.Property<int>("HumanResourceStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HumanResourceStatusId");

                    b.ToTable("HumanResourceStatus");

                    b.HasData(
                        new
                        {
                            HumanResourceStatusId = 1,
                            Name = "Approved"
                        },
                        new
                        {
                            HumanResourceStatusId = 2,
                            Name = "Pending"
                        },
                        new
                        {
                            HumanResourceStatusId = 3,
                            Name = "Disabled"
                        });
                });

            modelBuilder.Entity("Accredit.Shared.Entities.HumanResource", b =>
                {
                    b.HasOne("Accredit.Shared.Entities.HumanResourceStatus", "HumanResourceStatus")
                        .WithMany("HumanResources")
                        .HasForeignKey("HumanResourceStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
