// <auto-generated />
using System;
using Accredit.Domain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Accredit.Domain.Migrations
{
    [DbContext(typeof(HumanResourceContext))]
    [Migration("20211130215156_Correct-Employee-Numbers")]
    partial class CorrectEmployeeNumbers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Accredit.Shared.Entities.HumanResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("HumanResourceStatusId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("HumanResourceStatusId");

                    b.ToTable("HumanResources");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0e57407e-989c-4aae-a3c3-4843c553d418"),
                            CreatedDate = new DateTime(2021, 11, 30, 21, 51, 55, 851, DateTimeKind.Local).AddTicks(559),
                            DateOfBirth = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "IT",
                            Email = "jbloggs@hr.com",
                            EmployeeNumber = "01",
                            FirstName = "Joe",
                            HumanResourceStatusId = 1,
                            LastName = "Bloggs"
                        },
                        new
                        {
                            Id = new Guid("3610bb27-ce70-45b5-add4-722b98e5d83f"),
                            CreatedDate = new DateTime(2021, 11, 30, 21, 51, 55, 851, DateTimeKind.Local).AddTicks(6498),
                            DateOfBirth = new DateTime(2002, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Sales",
                            Email = "hpatel@hr.com",
                            EmployeeNumber = "02",
                            FirstName = "Harvey",
                            HumanResourceStatusId = 3,
                            LastName = "Patel"
                        },
                        new
                        {
                            Id = new Guid("20c3ecb7-1d83-4655-b354-423f925cd5e8"),
                            CreatedDate = new DateTime(2021, 11, 30, 21, 51, 55, 851, DateTimeKind.Local).AddTicks(6617),
                            DateOfBirth = new DateTime(1984, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Marketing",
                            Email = "shayes@hr.com",
                            EmployeeNumber = "03",
                            FirstName = "Simon",
                            HumanResourceStatusId = 1,
                            LastName = "Hayes"
                        },
                        new
                        {
                            Id = new Guid("33f45fa7-a3bd-4b2b-84df-0875db3d7c33"),
                            CreatedDate = new DateTime(2021, 11, 30, 21, 51, 55, 851, DateTimeKind.Local).AddTicks(6633),
                            DateOfBirth = new DateTime(1978, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "IT",
                            Email = "zmurphy@hr.com",
                            EmployeeNumber = "04",
                            FirstName = "Zoe",
                            HumanResourceStatusId = 2,
                            LastName = "Murphy"
                        },
                        new
                        {
                            Id = new Guid("30b8b676-79ee-4a9c-b5a8-7b708261ea38"),
                            CreatedDate = new DateTime(2021, 11, 30, 21, 51, 55, 851, DateTimeKind.Local).AddTicks(6648),
                            DateOfBirth = new DateTime(1994, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Call Center",
                            Email = "chawkins@hr.com",
                            EmployeeNumber = "05",
                            FirstName = "Charlie",
                            HumanResourceStatusId = 1,
                            LastName = "Hawkins"
                        },
                        new
                        {
                            Id = new Guid("4f542092-4053-4d57-8c6c-62124724164d"),
                            CreatedDate = new DateTime(2021, 11, 30, 21, 51, 55, 851, DateTimeKind.Local).AddTicks(6665),
                            DateOfBirth = new DateTime(1982, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "IT",
                            Email = "abishop@hr.com",
                            EmployeeNumber = "06",
                            FirstName = "Alisha",
                            HumanResourceStatusId = 1,
                            LastName = "Bishop"
                        });
                });

            modelBuilder.Entity("Accredit.Shared.Entities.HumanResourceStatus", b =>
                {
                    b.Property<int>("HumanResourceStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HumanResourceStatusId");

                    b.ToTable("HumanResourceStatus");

                    b.HasData(
                        new
                        {
                            HumanResourceStatusId = 1,
                            Name = "Approved"
                        },
                        new
                        {
                            HumanResourceStatusId = 2,
                            Name = "Pending"
                        },
                        new
                        {
                            HumanResourceStatusId = 3,
                            Name = "Disabled"
                        });
                });

            modelBuilder.Entity("Accredit.Shared.Entities.HumanResource", b =>
                {
                    b.HasOne("Accredit.Shared.Entities.HumanResourceStatus", "HumanResourceStatus")
                        .WithMany("HumanResources")
                        .HasForeignKey("HumanResourceStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
