// <auto-generated />
using System;
using Accredit.Domain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Accredit.Domain.Migrations
{
    [DbContext(typeof(HumanResourceContext))]
    partial class HumanResourceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Accredit.Shared.Entities.HumanResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("HumanResourceStatusId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("HumanResourceStatusId");

                    b.ToTable("HumanResources");
                });

            modelBuilder.Entity("Accredit.Shared.Entities.HumanResourceStatus", b =>
                {
                    b.Property<int>("HumanResourceStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HumanResourceStatusId");

                    b.ToTable("HumanResourceStatus");

                    b.HasData(
                        new
                        {
                            HumanResourceStatusId = 1,
                            Name = "Approved"
                        },
                        new
                        {
                            HumanResourceStatusId = 2,
                            Name = "Pending"
                        },
                        new
                        {
                            HumanResourceStatusId = 3,
                            Name = "Disabled"
                        });
                });

            modelBuilder.Entity("Accredit.Shared.Entities.HumanResource", b =>
                {
                    b.HasOne("Accredit.Shared.Entities.HumanResourceStatus", "HumanResourceStatus")
                        .WithMany("HumanResources")
                        .HasForeignKey("HumanResourceStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
